export const MOCK_CUSTOMERS = [
  {
    id: 'MC-2025-0041',
    name: 'Arjun Sharma',
    type: 'MSME',
    location: 'Delhi',
    loanAsk: 420000,
    modelPrediction: 'approve',
    suggestedPrincipal: 420000,
    suggestedRate: 11.5,
    submittedAt: '2h ago',
    status: 'active',
    shapFeatures: [
      { feature: 'Income regularity',    value: 0.82, impact: 'positive', desc: 'Consistent monthly credits' },
      { feature: 'Savings ratio',        value: 0.71, impact: 'positive', desc: 'Above-average savings' },
      { feature: 'Transaction history',  value: 0.65, impact: 'positive', desc: '18 months of clean data' },
      { feature: 'Existing obligations', value: 0.44, impact: 'neutral',  desc: 'Low existing debt' },
      { feature: 'Cash-flow volatility', value: 0.28, impact: 'negative', desc: 'Minor Q3 irregularities' },
    ],
  },
  {
    id: 'MC-2025-0042',
    name: 'Fatima Shaikh',
    type: 'Individual',
    location: 'Mumbai',
    loanAsk: 85000,
    modelPrediction: 'reject',
    suggestedPrincipal: 0,
    suggestedRate: 0,
    submittedAt: '3h ago',
    status: 'active',
    shapFeatures: [
      { feature: 'Transaction history',  value: 0.18, impact: 'negative', desc: 'Only 4 months of data' },
      { feature: 'Cash-flow volatility', value: 0.21, impact: 'negative', desc: 'Irregular income pattern' },
      { feature: 'Existing obligations', value: 0.19, impact: 'negative', desc: 'High EMI-to-income ratio' },
      { feature: 'Savings ratio',        value: 0.38, impact: 'neutral',  desc: 'Average savings behaviour' },
      { feature: 'Income regularity',    value: 0.45, impact: 'positive', desc: 'Some consistent credits' },
    ],
  },
  {
    id: 'MC-2025-0043',
    name: 'Ravi Patel',
    type: 'MSME',
    location: 'Ahmedabad',
    loanAsk: 210000,
    modelPrediction: 'approve',
    suggestedPrincipal: 180000,
    suggestedRate: 12.0,
    submittedAt: '5h ago',
    status: 'active',
    shapFeatures: [
      { feature: 'Income regularity',    value: 0.72, impact: 'positive', desc: 'Regular salary credits' },
      { feature: 'Transaction history',  value: 0.60, impact: 'positive', desc: '12 months of data' },
      { feature: 'Savings ratio',        value: 0.48, impact: 'neutral',  desc: 'Moderate savings' },
      { feature: 'Existing obligations', value: 0.35, impact: 'neutral',  desc: 'Moderate debt burden' },
      { feature: 'Cash-flow volatility', value: 0.30, impact: 'negative', desc: 'Some volatility detected' },
    ],
  },
  {
    id: 'MC-2025-0044',
    name: 'Sunita Verma',
    type: 'Individual',
    location: 'Pune',
    loanAsk: 150000,
    modelPrediction: 'approve',
    suggestedPrincipal: 150000,
    suggestedRate: 10.5,
    submittedAt: '6h ago',
    status: 'active',
    shapFeatures: [
      { feature: 'Income regularity',    value: 0.90, impact: 'positive', desc: 'Highly consistent income' },
      { feature: 'Savings ratio',        value: 0.80, impact: 'positive', desc: 'Excellent savings rate' },
      { feature: 'Transaction history',  value: 0.75, impact: 'positive', desc: '24 months of data' },
      { feature: 'Existing obligations', value: 0.60, impact: 'neutral',  desc: 'Some existing EMIs' },
      { feature: 'Cash-flow volatility', value: 0.20, impact: 'negative', desc: 'Minor fluctuations' },
    ],
  },
]

export const PREVIOUS_CUSTOMERS = [
  { id: 'MC-2025-0035', name: 'Meena Krishnan',  type: 'Individual', location: 'Chennai',   loanAsk: 200000, finalDecision: 'approved', rate: 11.0, submittedAt: '2 days ago' },
  { id: 'MC-2025-0036', name: 'Deepak Gupta',    type: 'MSME',       location: 'Jaipur',    loanAsk: 500000, finalDecision: 'approved', rate: 12.5, submittedAt: '2 days ago' },
  { id: 'MC-2025-0037', name: 'Priya Nair',      type: 'Individual', location: 'Kochi',     loanAsk: 75000,  finalDecision: 'rejected', rate: null,  submittedAt: '3 days ago' },
  { id: 'MC-2025-0038', name: 'Vikram Singh',    type: 'MSME',       location: 'Chandigarh',loanAsk: 300000, finalDecision: 'approved', rate: 11.8, submittedAt: '3 days ago' },
  { id: 'MC-2025-0039', name: 'Anjali Rao',      type: 'Individual', location: 'Hyderabad', loanAsk: 120000, finalDecision: 'rejected', rate: null,  submittedAt: '4 days ago' },
]
